#ifndef  __CONSTANT_H__
#define  __CONSTANT_H__

#define MELEE_SOLDIER_ATTACK 3
#define MELEE_SOLDIER_HP 15
#define MELEE_SOLDIER_MOVE_SPEED 150
#define LONG_REMOTE_SOLDIER_ATTACK 2
#define SHORT_REMOTE_SOLDIER_ATTACK 3
#define LONG_REMOTE_SOLDIER_ATTACK_RADIUS 50
#define SHORT_REMOTE_SOLDIER_ATTACK_RADIUS 20
#define REMOTE_SOLDIER_HP 10
#define REMOTE_SOLDIER_MOVE_SPEED 50
#define SOLDIER_ATTACK_INTERVAL 5
enum ESoldierType
{
	NARROWMELEE,
	WIDEMELLE,
	SHORTREMOTE,
	LONGREMOTE
};

#endif
