#ifndef  __CONSTANT_H__
#define  __CONSTANT_H__

#define PI 3.14
#define MELEE_SOLDIER_ATTACK 3
#define MELEE_SOLDIER_HP 15
#define MELEE_SOLDIER_MOVE_SPEED 150
#define LONG_REMOTE_SOLDIER_ATTACK 2
#define SHORT_REMOTE_SOLDIER_ATTACK 3
#define LONG_REMOTE_SOLDIER_ATTACK_RADIUS 300
#define SHORT_REMOTE_SOLDIER_ATTACK_RADIUS 100
#define REMOTE_SOLDIER_HP 10
#define REMOTE_SOLDIER_MOVE_SPEED 50
#define SOLDIER_ATTACK_INTERVAL 5
#define REMOTE_SOLDIER_TAG 2
#define SHORT_REMOTE_SOLDIER_TAG 10
#define LONG_REMOTE_SOLDIER_TAG 20
#define SOLDIER_BULLET_SPEED 100
#define MAX_REMOTE_SOLDIER_NUM 5

#define RED_BOTTLE 0
#define BLUE_BOTTLE 1
enum EActorType
{
	SHORTREMOTE,
	LONGREMOTE,
	NARROWMELEE,
	WIDEMELLE,
	PLAYER,
	PISTOLBULLET
	
};
enum EItemsType
{
	REDBOTTLE,
	BLUEBOTTLE
};
#endif
